export const servicesData =  {
    categories: ['All', 'Coffee', 'Pastries', 'Beans'],
    services: [
        { id: 1, image: '/img/Beans/bean-1.png', title: 'La Canada, Oaxaca, Mexico', category: 'Beans', description: 'Notes: Guayaba, Honey, Cacao', cost: 24 },
        { id: 2, image: '/img/Beans/bean-2.png', title: 'Community Blend', category: 'Beans', description: 'Notes: Chocolate, Nougat, and Subtle Fruit', cost: 19 },
        { id: 3, image: '/img/Beans/bean-3.png', title: 'Decaf - Colombia', category: 'Beans', description: 'Notes: Hazelnuts, Earthy, Toffee', cost: 23 },
        { id: 4, image: '/img/Beans/bean-4.png', title: 'El Crucero 4E', category: 'Beans', description: 'Process: Washed', cost: 23 },
        { id: 5, image: '/img/Beans/bean-5.png', title: 'Los Ventenos - Narino Colombia', category: 'Beans', description: 'Notes: Tropical Fruits, Butterscotch, Kumquat', cost: 21 },
        { id: 6, image: '/img/Beans/bean-6.png', title: 'Espanto Signature Blend', category: 'Beans', description: 'Notes: Fig, Red Fruits, Cacao', cost: 22 },
        { id: 7, image: '/img/Food/food-1.png', title: 'Baby Lime Pie', category: 'Pastries', description: 'Lime pie with a graham crust and creme fraiche whip', cost: 6.50 },
        { id: 8, image: '/img/Food/food-2.png', title: 'Fruit Tart', category: 'Pastries', description: 'Berry medley fruit tart with graham crust', cost: 6.50 },
        { id: 9, image: '/img/Food/food-3.png', title: 'Chocolate Chip Cookie', category: 'Pastries', description: 'A chocolate chip cookie that is 70% chocolate', cost: 6.50 },
        { id: 10, image: '/img/Food/food-4.png', title: 'Strawbs Jam Scone', category: 'Pastries', description: 'Whole grain scone life with strawberry jam', cost: 6.50 },
        { id: 11, image: '/img/Food/food-5.png', title: 'Peach, Olallie, and Raspberry Galette', category: 'Pastries', description: 'Galette with peach, olallie, and raspberry..and an edible flower', cost: 6.50 },
        { id: 12, image: '/img/Food/food-6.png', title: 'Banana Cream Pie', category: 'Pastries', description: 'Banana cream whip topping with a graham crust', cost: 12 },
        { id: 13, image: '/img/Coffee/coffee-1.jpg', title: 'The Coldest Brew', category: 'Coffee', description: 'Ingredients: Coffee and Water', cost: 6.50 },
        { id: 14, image: '/img/Coffee/coffee-2.jpg', title: 'It\'s Lavender, Hun', category: 'Coffee', description: 'Ingredients: Lavender, Honey, Coffee, Oat Milk', cost: 6.50 },
        { id: 15, image: '/img/Coffee/coffee-3.jpg', title: 'An Oat Milk Latte', category: 'Coffee', description: 'Ingredients: Coffee and Oat Milk', cost: 6.50 },
        { id: 16, image: '/img/Coffee/coffee-4.jpg', title: 'Passion for Mint', category: 'Coffee', description: 'Ingredients: Passion Fruit Juice, Mint Simple Syrup, Coffee, Oat Milk', cost: 6.50 },
        { id: 17, image: '/img/Coffee/coffee-5.jpg', title: 'The Rosie Mae Latte', category: 'Coffee', description: 'Ingredients: Rosemary, Maple, Coffee, Oat Milk', cost: 6.50 },
    ],
}